title: Alec Pokarier
baseURL: /
params:
  accent_color: blue
  color_scheme: light
  footer:
    content: '&copy; Stackbit-Exto. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    logo_img: /images/facebook-icon.png
    title: Exto
disableKinds:
  - RSS
