title: Alec Pokarier
baseURL: /
params:
  accent_color: blue
  color_scheme: light
  footer:
    content: '&copy; Alec Pokarier. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made by Blackwood Media
        url: 'http://www.blackwoodmedia.com.au'
  header:
    has_nav: true
    logo_img: /images/facebook-icon.png
    title: Exto
disableKinds:
  - RSS
